name: "Plugin Install Action"

on:
  workflow_call:
    inputs:
      plugin-key:
        required: true
        type: string

      repository:
        required: false
        type: string
        default: "itsmng"

jobs:
    ci:
        name: Install Plugin
        runs-on: ubuntu-latest
        container: 
            image: ghcr.io/itsmng/itsm-ng:latest
            env:
                MARIADB_HOST: mariadb
                MARIAD_USER: itsmng
                MARIADB_PASSWORD: itsmng
                MARIADB_DATABASE: itsmng

        services:
            mariadb:
                image: docker.io/mariadb:latest
                env:
                    MYSQL_ROOT_PASSWORD: itsmng
                    MYSQL_DATABASE: itsmng
                    MYSQL_USER: itsmng
                    MYSQL_PASSWORD: itsmng
                ports:
                    - 3306:3306

        steps:
            - name: Checkout
              working-directory: "/var/www/itsm-ng/plugins"
              run: |
                apt update
                apt install -y git
                git clone https://github.com/${{ inputs.repository }}/${{ inputs.plugin-key }}

            - name: "Install composer and nodejs"
              run: |
                apt update
                apt install -y composer nodejs

            - name: "Install dependencies"
              working-directory: "/var/www/itsm-ng"
              run: |
                if [ -f "composer.json" ]; then
                    composer install --ansi --no-interaction --no-progress --prefer-dist
                fi
                if [ -f "package.json" ]; then
                    npm install --no-save
                fi
            
            - name: "Install Plugin"
              working-directory: "/var/www/itsm-ng"
              run: |
               bin/console itsmng:database:install --ansi --no-interaction --db-name=itsmng --db-host=mariadb --db-user=itsmng --db-password=itsmng
               bin/console itsmng:plugin:install --ansi --no-interaction --username=itsm ${{ inputs.plugin-key }}
               bin/console itsmng:plugin:activate --ansi --no-interaction ${{ inputs.plugin-key }}
            